name: api
services:
    app-nginx:
        image: nginx:latest
        volumes:
            - app_data:/var/www
            - ./.deploy/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8000:8000"
        container_name: api_nginx
        depends_on:
            - app
        networks:
            - content_host_network
    app:
        build:
            context: .
            dockerfile: .deploy/Dockerfile
        environment:
            - APP_KEY=$APP_KEY
            - APP_NAME=$APP_NAME
            - APP_ENV=$APP_ENV
            - APP_URL=$APP_URL
            - FRONTEND_URL=$FRONTEND_URL
            - SESSION_DOMAIN=$SESSION_DOMAIN
            - SANCTUM_STATEFUL_DOMAINS=$SANCTUM_STATEFUL_DOMAINS
            - DB_CONNECTION=$DB_CONNECTION
            - DB_HOST=$DB_HOST
            - DB_PORT=$DB_PORT
            - DB_DATABASE=$DB_DATABASE
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
            - APP_DEBUG=$APP_DEBUG
        volumes:
            - app_data:/var/www
        #ports:
        #    - "9000:9000"
        container_name: api_app
        depends_on:
            - db
        networks:
            - content_host_network

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - content_host_network

networks:
    content_host_network:
        external: true

volumes:
    app_data:
    mysql_data:
