
services:
  nginx:
    image: my-nginx-app:latest
    container_name: nginx-container
    ports:
      - "8000:8000"
    volumes:
      - shared-data:/var/www
    networks:
      - app-network

  app:
    image: my-php-app:latest
    container_name: php-container
    volumes:
      - shared-data:/var/www
    networks:
      - app-network

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge
