
services:
  nginx:
    image: nginx:latest
    volumes:
      - app_data:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8878:80"
    container_name: photo_content_prod_nginx
    depends_on:
      - app
    networks:
      - photo_content_prod_network

  app:
    image: alonecat/photo_content_prod:latest  # Заменили build на image
    environment:
      - APP_KEY=$APP_KEY
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_URL=$APP_URL
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - APP_DEBUG=$APP_DEBUG
      - CURRENT_BRANCH=$CURRENT_BRANCH
      - LAST_COMMIT=$LAST_COMMIT
    volumes:
      - app_data:/var/www
    container_name: photo_content_prod_app
    depends_on:
      - db
    networks:
      - photo_content_prod_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3386:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: photo_content_prod_db
    networks:
      - photo_content_prod_network

networks:
  photo_content_prod_network:
    driver: bridge

volumes:
  app_data:
  mysql_data:
