services:
    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8879:80"
        container_name: photo_content_local_nginx
        depends_on:
            - app
        networks:
            - photo_content_local_network
    app:
        build:
            context: .
            dockerfile: ./_docker/app/local/Dockerfile
        environment:
            - APP_KEY=$APP_KEY
            - APP_NAME=$APP_NAME
            - APP_ENV=$APP_ENV
            - APP_URL=$APP_URL
            - DB_CONNECTION=$DB_CONNECTION
            - DB_HOST=$DB_HOST
            - DB_PORT=$DB_PORT
            - DB_DATABASE=$DB_DATABASE
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
            - APP_DEBUG=$APP_DEBUG
            - CURRENT_BRANCH=$CURRENT_BRANCH
            - LAST_COMMIT=$LAST_COMMIT
        volumes:
            - .:/var/www
        container_name: photo_content_local_app
        depends_on:
            - db
        networks:
            - photo_content_local_network

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_local_data:/var/lib/mysql
        container_name: photo_content_local_db
        networks:
            - photo_content_local_network

networks:
    photo_content_local_network:
        driver: bridge

volumes:
    mysql_local_data:
