entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  insecure: true
  entryPoint: "websecure"  # Используем HTTPS entryPoint
  port: 8082

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${TRAEFIK_EMAIL}"
      storage: acme.json
      httpChallenge:
        entryPoint: web  # Для HTTP-челленджа через entry point web
