name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build and Cache Docker Image"]  # Имя workflow для билда
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, macOs, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove old containers
        run: |
          export CONTAINER_PREFIX=photo_content
          docker stop $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
          docker rm $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
          sleep 5

      - name: Deploy to VPS (or local runner)
        run: |
          docker-compose up -d

