name: Build and Push Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for prod
      run: |
        docker build -f _docker/app/Dockerfile -t alonecat/photo_content_api_prod:latest .
        docker push alonecat/photo_content_api_prod:latest
  deploy:
    runs-on: vps
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up environment variables and deploy
        run: |
          export CONTAINER_PREFIX=photo_content
          docker stop $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
          docker rm $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
          sleep 5
      - name: Deploy to VPS
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_URL: ${{ secrets.APP_URL }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          APP_DEBUG: ${{ secrets.APP_DEBUG }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "APP_KEY=${APP_KEY}"
          echo "APP_NAME=${APP_NAME}"
          echo "APP_ENV=${APP_ENV}"
          echo "APP_URL=${APP_URL}"
          echo "DB_CONNECTION=${DB_CONNECTION}"
          echo "DB_HOST=${DB_HOST}"
          echo "DB_PORT=${DB_PORT}"
          echo "DB_DATABASE=${DB_DATABASE}"
          echo "DB_USERNAME=${DB_USERNAME}"
          echo "DB_PASSWORD=${DB_PASSWORD}"
          echo "APP_DEBUG=${APP_DEBUG}"
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          sleep 5
          docker-compose -f docker-compose.prod.yml up -d
          sleep 5



